AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'elastic-apm.gemspec'
    - 'vendor/**/*'

Layout/AlignHash:
  Exclude:
    - 'Gemfile'

Lint/RescueException:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Naming/PredicateName:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/elastic-apm.rb'

Style/Alias:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Rails/Delegate:
  Enabled: false
