---
version: '3.4'

services:
  mongodb:
    image: mongo:latest
    volumes: ['mongodata:/data/db']
    ports: ['27017:27017']

  specs:
    build:
      context: .
      args:
        BUNDLER_VERSION: '2.0.2'
    image: '$IMAGE_NAME'
    environment:
      HOME: '/tmp'
      MONGODB_URL: 'mongodb:27017'
    entrypoint:
      'spec/entrypoint.sh'
    tty: true
    volumes:
      - .:/app:cached
      - ./vendor:/vendor
    tmpfs:
      - /tmp:exec,mode=1777
    depends_on:
      - mongodb

volumes:
  vendor:
  mongodata:
