# frozen_string_literal: true

require 'bundler/gem_tasks'

desc """Post release action:
Update `3.x` branch to be at released commit and push it to GitHub.
"""
namespace :release do
  task :update_branch do
    `git checkout 3.x &&
    git rebase master &&
    git push origin 3.x &&
    git checkout master`
  end
end

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec)

require 'yard'
YARD::Rake::YardocTask.new
task docs: :yard

task default: :spec

namespace :coverage do
    desc "Collates all result sets generated by the different test runners"
    task :report do
      require 'simplecov'
      require 'simplecov-cobertura'
      SimpleCov.formatter = SimpleCov::Formatter::CoberturaFormatter
      SimpleCov.collate Dir["coverage/matrix_results/**/.resultset.json"]
    end
  end
