exclude:
  # Ruby 2.4
  # Only test on rails-4.2, sinatra-1.4
  - VERSION: ruby:2.4
    FRAMEWORK: rails-7.2
  - VERSION: ruby:2.4
    FRAMEWORK: rails-6.1
  - VERSION: ruby:2.4
    FRAMEWORK: rails-5.2
  - VERSION: ruby:2.4
    FRAMEWORK: sinatra-2.2
  - VERSION: ruby:2.4
    FRAMEWORK: grape-1.6
  - VERSION: ruby:2.4
    FRAMEWORK: rails-main
  - VERSION: ruby:2.4
    FRAMEWORK: sinatra-main
  - VERSION: ruby:2.4
    FRAMEWORK: grape-master

  # rails-4.2 exclusions
  # Only test on ruby 2.4
  - VERSION: ruby:3.1
    FRAMEWORK: rails-4.2
  - VERSION: ruby:2.7
    FRAMEWORK: rails-4.2
  - VERSION: ruby:2.6
    FRAMEWORK: rails-4.2
  - VERSION: jruby:9.2
    FRAMEWORK: rails-4.2
  - VERSION: elasticobservability/jruby:9.2-13-jdk
    FRAMEWORK: rails-4.2
  - VERSION: elasticobservability/jruby:9.2-11-jdk
    FRAMEWORK: rails-4.2
  - VERSION: elasticobservability/jruby:9.2-8-jdk
    FRAMEWORK: rails-4.2
  # sinatra-1.4 exclusions
  - VERSION: ruby:3.1
    FRAMEWORK: sinatra-1.4
  - VERSION: ruby:2.7
    FRAMEWORK: sinatra-1.4
  - VERSION: jruby:9.2
    FRAMEWORK: sinatra-1.4
  - VERSION: elasticobservability/jruby:9.2-13-jdk
    FRAMEWORK: sinatra-1.4
  - VERSION: elasticobservability/jruby:9.2-11-jdk
    FRAMEWORK: sinatra-1.4
  - VERSION: elasticobservability/jruby:9.2-8-jdk
    FRAMEWORK: sinatra-1.4

  # rails-6.1 and rails 7.0 exclusions
  # Don't test on ruby 2.4
  - VERSION: ruby:2.4
    FRAMEWORK: rails-6.1
  - VERSION: ruby:2.4
    FRAMEWORK: rails-7.2

  # Only test rails main on ruby 3.1
  - VERSION: ruby:2.7
    FRAMEWORK: rails-main
  - VERSION: ruby:2.6
    FRAMEWORK: rails-main
  - VERSION: ruby:2.4
    FRAMEWORK: rails-main
  - VERSION: jruby:9.2
    FRAMEWORK: rails-main
  - VERSION: elasticobservability/jruby:9.2-13-jdk
    FRAMEWORK: rails-main
  - VERSION: elasticobservability/jruby:9.2-11-jdk
    FRAMEWORK: rails-main
  - VERSION: elasticobservability/jruby:9.2-8-jdk
    FRAMEWORK: rails-main

  # Only test rails 7.2 on ruby >= 3.1
  - VERSION: ruby:2.7
    FRAMEWORK: rails-7.2
  - VERSION: ruby:2.6
    FRAMEWORK: rails-7.2
  - VERSION: ruby:2.4
    FRAMEWORK: rails-7.2
  - VERSION: jruby:9.2
    FRAMEWORK: rails-7.2
  - VERSION: elasticobservability/jruby:9.2-13-jdk
    FRAMEWORK: rails-7.2
  - VERSION: elasticobservability/jruby:9.2-11-jdk
    FRAMEWORK: rails-7.2
  - VERSION: elasticobservability/jruby:9.2-8-jdk
    FRAMEWORK: rails-7.2

  # Only test sinatra main on ruby 2.7 and ruby 3.1
  - VERSION: ruby:2.6
    FRAMEWORK: sinatra-main
  - VERSION: ruby:2.4
    FRAMEWORK: sinatra-main
  - VERSION: jruby:9.2
    FRAMEWORK: sinatra-main
  - VERSION: elasticobservability/jruby:9.2-13-jdk
    FRAMEWORK: sinatra-main
  - VERSION: elasticobservability/jruby:9.2-11-jdk
    FRAMEWORK: sinatra-main
  - VERSION: elasticobservability/jruby:9.2-8-jdk
    FRAMEWORK: sinatra-main

  # Only test grape master on ruby 2.7 and ruby 3.1
  - VERSION: ruby:2.6
    FRAMEWORK: grape-master
  - VERSION: ruby:2.4
    FRAMEWORK: grape-master
  - VERSION: jruby:9.2
    FRAMEWORK: grape-master
  - VERSION: elasticobservability/jruby:9.2-13-jdk
    FRAMEWORK: grape-master
  - VERSION: elasticobservability/jruby:9.2-11-jdk
    FRAMEWORK: grape-master
  - VERSION: elasticobservability/jruby:9.2-8-jdk
    FRAMEWORK: grape-master

  # grape 1.5 doesn't support ruby 3.1
  - VERSION: ruby:3.1
    FRAMEWORK: grape-1.6

  # only test ruby >= 3.1 with rails 6.1 and rails 7.0
  - VERSION: ruby:3.1
    FRAMEWORK: rails-5.2
  - VERSION: ruby:3.1
    FRAMEWORK: rails-5.1
