exclude:
  # Ruby 2.3
  # Only includes rails-5.2, sinatra-2.0
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: rails-6.1
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: rails-6.0
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: sinatra-1.4
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: grape-1.5
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: grape-1.5,sinatra-2.0,rails-6.0
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: rails-master
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: grape-master

  # rails-4.2 exclusions
  # Only test on ruby 2.6, 2.5, 2.4, 2.3
  - RUBY_VERSION: ruby:3.0
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: ruby:2.7
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: jruby:9.2
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-13-jdk
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-11-jdk
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-8-jdk
    FRAMEWORK: rails-4.2

  # rails-6.0 and rails-6.1 exclusions
  # Don't test on ruby 2.4
  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: rails-6.1
  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: rails-6.0

  # Only test rails master on ruby 2.7 and ruby 3.0
  - RUBY_VERSION: ruby:2.6
    FRAMEWORK: rails-master
  - RUBY_VERSION: ruby:2.5
    FRAMEWORK: rails-master
  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: rails-master
  - RUBY_VERSION: jruby:9.2
    FRAMEWORK: rails-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-13-jdk
    FRAMEWORK: rails-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-11-jdk
    FRAMEWORK: rails-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-8-jdk
    FRAMEWORK: rails-master

  # Only test sinatra master on ruby 2.7 and ruby 3.0
  - RUBY_VERSION: ruby:2.6
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: ruby:2.5
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: jruby:9.2
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-13-jdk
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-11-jdk
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-8-jdk
    FRAMEWORK: sinatra-master

  # Only test grape master on ruby 2.7 and ruby 3.0
  - RUBY_VERSION: ruby:2.6
    FRAMEWORK: grape-master
  - RUBY_VERSION: ruby:2.5
    FRAMEWORK: grape-master
  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: grape-master
  - RUBY_VERSION: jruby:9.2
    FRAMEWORK: grape-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-13-jdk
    FRAMEWORK: grape-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-11-jdk
    FRAMEWORK: grape-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-8-jdk
    FRAMEWORK: grape-master

  # grape 1.5 doesn't support ruby 3.0
  - RUBY_VERSION: ruby:3.0
    FRAMEWORK: grape-1.5
  - RUBY_VERSION: ruby:3.0
    FRAMEWORK: grape-1.5,sinatra-2.0,rails-6.1

  # only test ruby 3.0 with rails 6.0 and rails 6.1
  - RUBY_VERSION: ruby:3.0
    FRAMEWORK: rails-5.2
  - RUBY_VERSION: ruby:3.0
    FRAMEWORK: rails-5.1

  # Unsupported
  - RUBY_VERSION: ruby:2.6
    FRAMEWORK: grape-1.5,sinatra-2.0,rails-6.1
  - RUBY_VERSION: ruby:2.5
    FRAMEWORK: grape-1.5,sinatra-2.0,rails-6.1
  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: grape-1.5,sinatra-2.0,rails-6.1
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: grape-1.5,sinatra-2.0,rails-6.1
  - RUBY_VERSION: jruby:9.2
    FRAMEWORK: grape-1.5,sinatra-2.0,rails-6.1
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-13-jdk
    FRAMEWORK: grape-1.5,sinatra-2.0,rails-6.1
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-11-jdk
    FRAMEWORK: grape-1.5,sinatra-2.0,rails-6.1
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-8-jdk
    FRAMEWORK: grape-1.5,sinatra-2.0,rails-6.1
