exclude:
  # Ruby 2.3
  # Only includes rails-5.2, sinatra-2.0
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: rails-6.0
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: rails-5.1
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: rails-5.0
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: sinatra-1.4
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: grape-1.3
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: rails-master
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: ruby:2.3
    FRAMEWORK: grape-master

  - RUBY_VERSION: ruby:2.7
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: jruby:9.2
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: jruby:9.1
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-13-jdk
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-12-jdk
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-11-jdk
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-8-jdk
    FRAMEWORK: rails-4.2
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.1-7-jdk
    FRAMEWORK: rails-4.2

  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: rails-6.0
  - RUBY_VERSION: jruby:9.1
    FRAMEWORK: rails-6.0
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.1-7-jdk
    FRAMEWORK: rails-6.0

  # Only test master on newest ruby
  - RUBY_VERSION: ruby:2.6
    FRAMEWORK: rails-master
  - RUBY_VERSION: ruby:2.5
    FRAMEWORK: rails-master
  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: rails-master
  - RUBY_VERSION: jruby:9.2
    FRAMEWORK: rails-master
  - RUBY_VERSION: jruby:9.1
    FRAMEWORK: rails-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-13-jdk
    FRAMEWORK: rails-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-12-jdk
    FRAMEWORK: rails-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-11-jdk
    FRAMEWORK: rails-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-8-jdk
    FRAMEWORK: rails-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.1-7-jdk
    FRAMEWORK: rails-master

  - RUBY_VERSION: ruby:2.5
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: jruby:9.2
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: jruby:9.1
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-13-jdk
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-12-jdk
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-11-jdk
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-8-jdk
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.1-7-jdk
    FRAMEWORK: sinatra-master

  - RUBY_VERSION: ruby:2.6
    FRAMEWORK: grape-master
  - RUBY_VERSION: ruby:2.5
    FRAMEWORK: grape-master
  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: grape-master
  - RUBY_VERSION: jruby:9.2
    FRAMEWORK: grape-master
  - RUBY_VERSION: jruby:9.1
    FRAMEWORK: grape-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-13-jdk
    FRAMEWORK: grape-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-12-jdk
    FRAMEWORK: grape-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-11-jdk
    FRAMEWORK: grape-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-8-jdk
    FRAMEWORK: grape-master
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.1-7-jdk
    FRAMEWORK: grape-master

  # Unsupported
  - RUBY_VERSION: jruby:9.1
    FRAMEWORK: grape-1.3
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.1-7-jdk
    FRAMEWORK: grape-1.3

  - RUBY_VERSION: ruby:2.6
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
  - RUBY_VERSION: ruby:2.5
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
  - RUBY_VERSION: ruby:2.4
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
  - RUBY_VERSION: jruby:9.2
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
  - RUBY_VERSION: jruby:9.1
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-13-jdk
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-12-jdk
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-11-jdk
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.2-8-jdk
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
  - RUBY_VERSION: docker.elastic.co/observability-ci/jruby:9.1-7-jdk
    FRAMEWORK: grape-1.3,sinatra-2.0,rails-6.0
