#!/usr/bin/env groovy
@Library('apm@current') _

import co.elastic.matrix.*
import groovy.transform.Field

/**
This is the parallel tasks generator,
it is need as field to store the results of the tests.
*/
@Field def rubyTasksGen

pipeline {
  agent any
  environment {
    REPO = 'apm-agent-ruby'
    BASE_DIR = "src/github.com/elastic/${env.REPO}"
    PIPELINE_LOG_LEVEL='INFO'
    NOTIFY_TO = credentials('notify-to')
    JOB_GCS_BUCKET = credentials('gcs-bucket')
    CODECOV_SECRET = 'secret/apm-team/ci/apm-agent-ruby-codecov'
    DOCKER_REGISTRY = 'docker.elastic.co'
    DOCKER_SECRET = 'secret/apm-team/ci/docker-registry/prod'
    GITHUB_CHECK_ITS_NAME = 'Integration Tests'
    ITS_PIPELINE = 'apm-integration-tests-selector-mbp/master'
  }
  options {
    timeout(time: 2, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    rateLimitBuilds(throttle: [count: 60, durationName: 'hour', userBoost: true])
    quietPeriod(10)
  }
  triggers {
    issueCommentTrigger('(?i).*(?:jenkins\\W+)?run\\W+(?:the\\W+)?tests(?:\\W+please)?.*')
  }
  parameters {
    booleanParam(name: 'Run_As_Master_Branch', defaultValue: false, description: 'Allow to run any steps on a PR, some steps normally only run on master branch.')
    booleanParam(name: 'bench_ci', defaultValue: true, description: 'Enable run benchmarks.')
  }
  stages {
    /**
    Checkout the code and stash it, to use it on other stages.
    */
    stage('Checkout') {
      agent { label 'master || immutable' }
      options { skipDefaultCheckout() }
      steps {
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}", githubNotifyFirstTimeContributor: true)
        stash allowEmpty: true, name: 'source', useDefaultExcludes: false
      }
    }
    /**
    Execute unit tests.
    */
    stage('Test') {
      agent { label 'linux && immutable' }
      options { skipDefaultCheckout() }
      steps {
        withGithubNotify(context: 'Tests', tab: 'tests') {
          deleteDir()
          unstash "source"
          dir("${BASE_DIR}"){
            script {
              def ruby = readYaml(file: '.ci/.jenkins_ruby.yml')
              def testTasks = [:]
              ruby['RUBY_VERSION'].each{ rubyVersion ->
                testTasks[rubyVersion] = { runJob(rubyVersion) }
              }
              parallel(testTasks)
              }
            }
          }
        }
      }
      stage('Benchmarks') {
        options { skipDefaultCheckout() }
        when {
          beforeAgent true
          allOf {
            anyOf {
              branch 'master'
              branch "\\d+\\.\\d+"
              branch "v\\d?"
              tag "v\\d+\\.\\d+\\.\\d+*"
              expression { return params.Run_As_Master_Branch }
            }
            expression { return params.bench_ci }
          }
        }
        stages {
          stage('Clean Workspace') {
            agent { label 'metal' }
            steps {
              echo "Cleaning Workspace"
            }
            post {
              always {
                cleanWs()
              }
            }
          }
          /**
            Run the benchmarks and store the results on ES.
            The result JSON files are also archive into Jenkins.
          */
          stage('Run Benchmarks') {
            agent { label 'linux && immutable' }
            steps {
              withGithubNotify(context: 'Run Benchmarks') {
                deleteDir()
                unstash 'source'
                dir("${BASE_DIR}"){
                  script {
                    def versions = readYaml(file: ".ci/.jenkins_ruby.yml")
                    def benchmarkTask = [:]
                    versions['RUBY_VERSION'].each{ v ->
                      benchmarkTask[v] = runBenchmark(v)
                    }
                    parallel(benchmarkTask)
                  }
                }
              }
            }
          }
        }
      }
      stage('Integration Tests') {
        agent none
        when {
          beforeAgent true
          allOf {
            anyOf {
              environment name: 'GIT_BUILD_CAUSE', value: 'pr'
              expression { return !params.Run_As_Master_Branch }
            }
          }
        }
        steps {
          log(level: 'INFO', text: 'Launching Async ITs')
          build(job: env.ITS_PIPELINE, propagate: false, wait: false,
                parameters: [string(name: 'AGENT_INTEGRATION_TEST', value: 'Ruby'),
                             string(name: 'BUILD_OPTS', value: "--ruby-agent-version ${env.GIT_BASE_COMMIT} --ruby-agent-version-state ${env.GIT_BUILD_CAUSE} --ruby-agent-repo ${env.CHANGE_FORK?.trim() ?: 'elastic'}/${env.REPO}"),
                             string(name: 'GITHUB_CHECK_NAME', value: env.GITHUB_CHECK_ITS_NAME),
                             string(name: 'GITHUB_CHECK_REPO', value: env.REPO),
                             string(name: 'GITHUB_CHECK_SHA1', value: env.GIT_BASE_COMMIT)]
          )
          githubNotify(context: "${env.GITHUB_CHECK_ITS_NAME}", description: "${env.GITHUB_CHECK_ITS_NAME} ...", status: 'PENDING', targetUrl: "${env.JENKINS_URL}search/?q=${env.ITS_PIPELINE.replaceAll('/','+')}")
        }
      }
    }
    post {
      cleanup {
        notifyBuildResult()
      }
    }
  }

/**
  Run benchmarks for a Ruby version, then report the results to the Elasticsearch server.
*/
def runBenchmark(version){
  return {
    node('metal'){
      // Transform the versions like:
      //  - docker.elastic.co/observability-ci/jruby:9.2-12-jdk to jruby-9.2-12-jdk
      //  - jruby:9.1 to jruby-9.1
      def transformedVersion = version.replaceAll('.*/', '').replaceAll(':', '-')
      env.HOME = "${env.WORKSPACE}/${transformedVersion}"
      dir("${transformedVersion}"){
        deleteDir()
        unstash 'source'
        dir("${BASE_DIR}"){
          retry(2){
            sleep randomNumber(min:10, max: 30)
            dockerLogin(secret: "${DOCKER_SECRET}", registry: "${DOCKER_REGISTRY}")
          }
          try{
            sh "./spec/scripts/benchmarks.sh ${version}"
          } catch(e){
            throw e
          } finally {
            archiveArtifacts(
              allowEmptyArchive: true,
              artifacts: "**/benchmark-${transformedVersion}.raw,**/benchmark-${transformedVersion}.error",
              onlyIfSuccessful: false)
            sendBenchmarks(file: "benchmark-${transformedVersion}.bulk",
              index: "benchmark-ruby", archive: true)
          }
        }
      }
    }
  }
}

def runJob(rubyVersion){
  def branch = env.BRANCH_NAME

  if (env.CHANGE_ID) {
    branch = env.CHANGE_TARGET
  }
  
  build( job: "apm-agent-ruby/apm-agent-ruby-downstream/${branch}", 
    parameters: [
      string(name: 'RUBY_VERSION', value: "${rubyVersion}"), 
      string(name: 'BRANCH_SPECIFIER', value: "${env.GIT_BASE_COMMIT}"), 
      string(name: 'MERGE_TARGET', value: "${branch}")
    ], 
    quietPeriod: 15
  )
}
