FRAMEWORK:
  - sinatra-1.4
  - sinatra-2.0
  - rails-5.2
  - rails-5.1
  - rails-5.0
  - rails-4.2
  - rails-4.1
  - rails-4.0
  # - rails-3.2.22
  # - rails-3.1.12
  # - rails-3.0.20
  # - rails-master
  - sinatra-master
