exclude:
  # Unsupported by Rails
  - RUBY_VERSION: ruby-2.4
    FRAMEWORK: rails-4.1
  - RUBY_VERSION: ruby-2.4
    FRAMEWORK: rails-4.0

  # Only test master on newest ruby
  - RUBY_VERSION: ruby-2.3
    FRAMEWORK: rails-master
  - RUBY_VERSION: jruby-9.1
    FRAMEWORK: rails-master

  - RUBY_VERSION: ruby-2.3
    FRAMEWORK: sinatra-master
  - RUBY_VERSION: jruby-9.1
    FRAMEWORK: sinatra-master
