---
version: '3.4'

services:
  mongodb:
    image: mongo:3.6
    volumes: ['mongodata:/data/db']
    ports: ['27017:27017']

  ruby_rspec:
    image: apm-agent-ruby:${RUBY_VERSION}
    environment:
      MONGODB_URL: 'mongodb:27017'

  runner:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
      args:
        RUBY_IMAGE: "ruby:latest"
        BUNDLER_VERSION: '2.0.2'
    command: "/bin/bash"
    environment:
      MONGODB_URL: 'mongodb:27017'
    entrypoint:
      'spec/entrypoint.sh'
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
    volumes:
      - ..:/app:cached
      - vendor:/vendor
    tmpfs:
      - /tmp

volumes:
  mongodata:
  vendor:
    driver: local
