---
version: '2.1'

services:
  mongodb:
    image: mongo:3.6
    volumes: ['mongodata:/data/db']
    ports: ['27017:27017']

  ruby_rspec:
    image: apm-agent-ruby:${RUBY_VERSION}
    environment:
      MONGODB_URL: 'mongodb:27017'

volumes:
  mongodata:
    driver: local
