[[introduction]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at
https://www.elastic.co/guide/en/apm/agent/ruby/current/introduction.html[elastic.co]
endif::[]

== Introduction

Welcome to the APM Ruby Agent documentation.

The Elastic APM Ruby Agent sends performance metrics and error logs to an
Elastic APM Server.
It has built-in support for <<getting-started-rails,Ruby on Rails>> and other
<<getting-started-rack,Rack-compatible>> applications.

[float]
[[additional-components]]
=== Additional Components

APM Agents work in conjunction with the {apm-server-ref-v}/index.html[APM Server], {ref}/index.html[Elasticsearch], and {kibana-ref}/index.html[Kibana].
Please view the {apm-overview-ref-v}/index.html[APM Overview] for details on how these components work together. 

[float]
[[framework-support]]
=== Framework Support

The Elastic APM Ruby Agent officially supports Ruby on Rails versions 4.x on
onwards, see <<getting-started-rails,Getting started with Ruby on Rails>>.

For Sinatra and other Rack compatible frameworks, see
<<getting-started-rack,Getting started with Rack>>.