---
name: github-commands-comment

on:
  pull_request_target:
    types:
      - opened

permissions:
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const body = `
              ### :robot: GitHub comments

              <details><summary>Expand to view the GitHub comments</summary>
              <p>

              Just comment with:
              - `run` `docs-build` : Re-trigger the docs validation. (use unformatted text in the comment!)
              </p>
              </details>
            `.replace(/  +/g, '')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
