on: push
name: Linting
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Rubocop
        uses: gimenete/rubocop-action@649c2b18b5726302b6b120dad74c25d2b2f391e9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
