---
## Workflow to process the JUnit test results and add a report to the checks.
name: test-reporter
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/oblt-actions/test-report@v1
        with:
          artifact: /test-results(.*)/
          name: 'Test Report $1'
          path: "**/*ruby-agent-junit.xml"
          reporter: java-junit
