---
## Workflow to process the JUnit test results and add a report to the checks.
name: test-reporter
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

permissions:
  contents: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/test-report@current
        with:
          artifact: test-results
          name: test-report
          path: "**/*ruby-agent-junit.xml"
          reporter: java-junit
